### ISSUE TITLE
Perimeter Crosshair box is drawn incorrectly.

### ISSUE THREAD

**Issue by BlueFinBima** [BlueFinBima/DCS-The-Way#2]
The perimeter box which denotes a partial screen is not being drawn correctly.  Likely to be that the vertical lines are too long.

**Comment by BlueFinBima** [comment]
Not sure if my monitor is hiding the last row of pixels, or whether the drawRect(0,0,2560,1440) isn't quite working as advertised, but can't get too excited about not seeing the lower line in the rectangle.   There might have once been another problem, but if there was, it should have been addressed by https://github.com/BlueFinBima/DCS-The-Way/commit/9fe6aa7cd969e78bb93cbd33e2555a7304156594 .  Closing because this is really a non-problem.

**Comment by GoldJohnKing** [comment]
Hi, the reference dot does not show on my screen at all.

I am using [6bc056c](https://github.com/BlueFinBima/DCS-The-Way/commit/6bc056ce956f001b3a2ce2feb3236338f99e6c69).

![QQ图片20230104113040](https://user-images.githubusercontent.com/26923626/210479576-5f02a531-8e95-40f7-af7e-d0aba43e8bba.jpg)

**Comment by BlueFinBima** [comment]
@GoldJohnKing Have you told the program which display is being used for F10?
```-d,--displaynumber <displaynumber>        Number of the display device  used for the F10 screen```

**Comment by GoldJohnKing** [comment]
> @GoldJohnKing Have you told the program which display is being used for F10? `-d,--displaynumber <displaynumber> Number of the display device used for the F10 screen`

I did this and the crosshair goes alright. I am just curious if main window knows which screen to display, why not the crosshair? 😕
