### ISSUE TITLE
Please merge support for KA-50 3

### ISSUE THREAD

**Issue by TAGE7** [BlueFinBima/DCS-The-Way#4]
Hi there,

Since you are way more active and your fork has a lot better features, can you please merge and compile w/ this change so we can use the awesome Way Changer + the Way on the KA-50 3?

https://github.com/aronCiucu/DCSTheWay/pull/47/commits/149640c81e11c9adbf6edef8bb4ab49ae0284495

EDIT: Please close, this is better suited for another fork

https://github.com/okopanja/DCSTheWay/compare/add_Ka-50_ABRIS...seven2099:DCSTheWay:patch-1

**Comment by seven2099** [comment]
Actually this is better suited for this fork.

https://github.com/okopanja/DCSTheWay/compare/add_Ka-50_ABRIS...seven2099:DCSTheWay:patch-1

**Comment by BlueFinBima** [comment]
Apologies for the very delayed response.  I have not been actively working on this fork for quite some time and I am not taking requirements on this fork
