### ISSUE TITLE
AV8B Harrier - record and enter altitude for waypoints

### ISSUE THREAD

**Issue by SomethingSimpl** [BlueFinBima/DCS-The-Way#6]
Hi, since a recent update to Harrier put in a requirement to manually set the altitude of the waypoints instead of the jet knowing and entering the altitude by itself would it be possible to make that happen with the automated script similar to the other modules TheWay supports? It currently doesnt touch the waypoint altitude at all.

**Comment by BlueFinBima** [comment]
@SomethingSimpl  Apologies for the very delayed response.  I have not been actively working on this fork for quite some time and I am not taking requirements on this fork
